### ISSUE TITLE
NPE generating docs....

### ISSUE THREAD

**Issue by spyhunter99** [jagregory/docu#9]
Not sure what i'm doing wrong. Just checked out docu, built it ok via visual studio and attempted to run it. Got this:

````
Unhandled Exception: System.NullReferenceException: There was no namespace found for schema, juddi-dotnet-client, Version=3.2.1.0, Culture=neutral, PublicKeyToken=null
   at Docu.Documentation.Generators.NamespaceGenerator.Add(List`1 namespaces, IDocumentationMember association) in C:\projects\docu\src\Docu.Console\Documentation\Generators\NamespaceGenerator.cs:line 23
   at Docu.Documentation.Generators.GenerationStep`1.<Docu.Documentation.Generators.IGenerationStep.get_Action>b__8_0(List`1 x, IDocumentationMember y) in C:\projects\docu\src\Docu.Console\Documentation\Generators\GenerationStep.cs:line 23
   at Docu.Documentation.DocumentModel.Create(IEnumerable`1 members) in C:\projects\docu\src\Docu.Console\Documentation\DocumentModel.cs:line 58
   at Docu.Parsing.AssemblyXmlParser.CreateDocumentModel(IEnumerable`1 assemblies, IEnumerable`1 xmlDocumentContents) in C:\projects\docu\src\Docu.Console\Parsing\AssemblyXmlParser.cs:line 28
   at Docu.DocumentationGenerator.Generate() in C:\projects\docu\src\Docu.Console\DocumentationGenerator.cs:line 87
   at Docu.Console.ConsoleApplication.Run() in C:\projects\docu\src\Docu.Console\Console\ConsoleApplication.cs:line 97
   at Docu.Console.ConsoleApplication.Run(IEnumerable`1 args) in C:\projects\docu\src\Docu.Console\Console\ConsoleApplication.cs:line 266
   at Docu.Program.Main(String[] args) in C:\projects\docu\src\Docu.Console\Program.cs:line 9
````

**Comment by spyhunter99** [comment]
looks like i have a chunk of code that was generated by one of the xsd to code generators that does not have a namespace declared. I was able to patch up docu to work around the issue by creating a fake namespace instance "NoNamespace". This works around the issue, however in the output, the left menu lists "NoNamespace" but does not render it clickable. The output is generated though. I'll open a PR if you like. Love the output style, it's very similar to javadocs which is exactly what i was looking for.
